spring:
  application:
    name: novoanjo
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:mysql://${DB_HOST}/novoanjo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    format-sql: false
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

service:
  scheduler:
    cron: "0 0/10 * * * *"
    time-zone: America/Sao_Paulo
