spring:
  application:
    name: novoanjo
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:mysql://localhost:3306/novoanjo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: jesus
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    format-sql: false
    open-in-view: false

