spring:
  application:
    name: novoanjo
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/novoanjo
    username: postgres
    password: jesus
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    format-sql: true
    open-in-view: false

