version: '3.1'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql
    container_name: db_novoanjo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jesus
      MYSQL_DATABASE: novoanjo
    ports:
      - "3306:3306"
    volumes:
      - ~/develop/docker/volumes/mysql:/var/lib/mysql
    networks:
      - novoanjo-network

networks:
  novoanjo-network:
    driver: bridge
