version: '3.1'

services:
  postgres:
    image: postgres:12-alpine
    container_name: db_novoanjo
    environment:
      POSTGRES_PASSWORD: jesus
      POSTGRES_DB: novoanjo
    ports:
      - "5432:5432"
    networks:
      - novoanjo-network

networks:
  novoanjo-network:
    driver: bridge
